#!/bin/sh
. /usr/shell/_utilities
#------------------------------------------------------------------------------
# uuptime - uptime with unique user count for system status reporting
#------------------------------------------------------------------------------
USER_COUNT=$(count_unique_users)
if [ $USER_COUNT -eq 1 ]; then
  OUT=$(uptime | sed "s/ users,/ sessions, $USER_COUNT user,/g")
else
  OUT=$(uptime | sed "s/ users,/ sessions, $USER_COUNT users,/g")
fi
OUT=$(text_remove_excess_spaces "$OUT")
echo $OUT
