#!/bin/sh
#-----------------------------------------------------------------------------
# NTS shell utilities standard library for networking
#-----------------------------------------------------------------------------
PING_BINARY=$(which ping 2>/dev/null)
USE_PING=$?
FPING_BINARY=$(which fping 2>/dev/null)
USE_FPING=$?
FPING_TIMEOUT_MS=500
#-----------------------------------------------------------------------------

check_host_alive () {
  if [ "$USE_FPING" -eq 0 ]; then
  # fping is a faster method, but not always available
    $FPING_BINARY -q -r 0 -t $FPING_TIMEOUT_MS "$1"
    echo $?
    return $?
  elif [ "$USE_PING" -eq 0 ]; then
  # fall back to attempting default ping method
    $PING_BINARY -w 1 -c 1 "$1" > /dev/null
    echo $?
    return $?
  fi
  echo "2"
  return 2 
}

check_host_port () {
  if [ -f $(which nc) ]; then
    nc -z -w 1 "$1" "$2" 1>/dev/null 2>/dev/null
    echo $?
    return $?
  fi
}
